# Agent Registry System (Consolidated v0.2.2)
# Dynamic agent discovery, registration, and management with domain expertise integration and adaptive capabilities

metadata:
  name: "agent_registry"
  version: "0.2.2"
  description: "Consolidated agent registry system with dynamic discovery, registration, and adaptive agent management with domain expertise integration and competency tracking"
  author: "Master Agent System v0.2.2"
  tags: ["agent-registry", "dynamic-discovery", "agent-management", "domain-expertise", "capability-tracking"]

# Registry Architecture Overview
registry_architecture:
  registration_system:
    description: "Dynamic agent registration system with auto-discovery capabilities"
    responsibilities:
      - Dynamic agent discovery across multiple sources
      - Agent validation and capability assessment
      - Dynamic name generation and categorization
      - Registry maintenance and updates
      - Backup and recovery mechanisms

  storage_system:
    description: "Reliable data storage with automatic backup"
    storage_layers:
      primary: "Memory with file backup"
      secondary: "Cache layer with TTL management"
      tertiary: "File system storage"

  cache_system:
    description: "Intelligent caching for performance optimization"
    cache_layers:
      l1_cache: "Active agent registry data"
      l2_cache: "Recent queries and frequently used data"
      l3_cache: "Historical agent data and performance metrics"

# Enhanced Agent Discovery System
agent_discovery_system:
  discovery_sources:
    filesystem_scan:
      enabled: true
      scan_paths:
        - "agents/"
        - "subagents/"
        - ".claude/agents/"
        - "system/agents/"
        - "user/agents/"
      file_patterns: ["*.md", "*.yaml", "*.json"]
      extraction_method: "yaml_frontmatter"
      fallback_on_empty: true

    agent_categories:
      development:
        enabled: true
        patterns:
          - "frontend", "ui", "ux", "css", "javascript", "react", "vue", "angular"
          "backend", "api", "server", "database", "microservice"
          "fullstack", "development"
          "coding", "programming", "implementation"
          "build", "create", "develop", "code"

      operations:
        enabled: true
        patterns:
          - "devops", "deployment", "infrastructure"
          - "ci", "pipeline", "build", "test", "deploy"
          - "cloud", "infrastructure", "cloud_platform", "hosting"
          - "monitoring", "observability", "alerting", "logging"

      testing:
        enabled: true
        patterns:
          - "test", "testing", "qa", "quality"
          - "automation", "automated", "e2e"
          - "validate", "verify", "qa", "quality"

      security:
        enabled: true
        patterns:
          - "security", "security_audit", "vulnerability", "penetration"
          - "authentication", "authorization", "access_control", "identity"
          - "encryption", "cryptography", "privacy"
          - "compliance", "audit", "governance"

      research:
        enabled: true
        patterns:
          - "research", "analyze", "investigate", "explore"
          - "analysis", "study", "examine", "investigate"
          - "explore", "discover", "study", "analyze"

      performance:
        enabled: true
        patterns:
          - "optimize", "performance", "optimization", "speed"
          - "tune", "benchmark", "performance_test"
          - "monitoring", "performance_tracking"

      architecture:
        enabled: true
        patterns:
          - "architecture", "design", "system_architecture", "patterns"
          - "scalability", "scalable", "architecture", "system_architecture"
          - "design_patterns", "pattern", "architectural_pattern"
          - "system_design", "software_design", "software_architecture"

    agent_validation:
      enabled: true
      validation_rules:
        name_validation:
          - "simple-name: '^[a-zA-Z][a-zA-Z0-9_-]+$'  # Accepts simple names only"
          - max_length: 50
          - no_spaces: true
          - no_special_characters: true
        capability_validation:
          - required_capabilities: "array"
          - check_availability: true
          - check_responsive: true
          - check_compatibility: true

        fallback_handling:
          invalid_name_format: "convert_to_lowercase_and_validate"
          missing_capabilities: "request_basic_capabilities"
          unavailable_agent: "mark_as_unavailable"

# Enhanced Domain Integration
domain_integration:
  domain_system_integration:
    integration_enabled: true
    domain_sources:
      - "domain_system.yaml"
      "agent_selection.yaml"
      "task_analysis.yaml"
      "clarification.yaml"
    integration_points:
      - TF-IDF domain matching for semantic relevance
      - Domain expertise alignment scoring
      - Dynamic category discovery

    dynamic_domain_categorization:
      enabled: true
      learning_enabled: true
      confidence_threshold: 0.7
      semantic_analysis: true
      pattern_recognition: true

# Enhanced Registration System
agent_registration_system:
  registration_process:
  automatic_registration:
    enabled: true
    auto_categorization: true
    confidence_threshold: 0.6
    dynamic_name_generation: true

  name_generation:
  strategy: "category-based"
  format_template: "{category}:{agent_name}"
  auto_increment: true

  registration_validation:
  enabled: true
  validation_rules:
    - Name must match simple-name format
    - Required capabilities must be available
    - Agent must be responsive and available

  cache_registration:
  enabled: true
  cache_duration: 3600  # 1 hour
  auto_cleanup: true

# Dynamic Capability Registry
capability_registry:
  capability_categories:
  technical_skills:
    programming_languages:
      examples: ["python", "javascript", "java", "go", "rust", "typescript", "php", "ruby", "c++"]
      importance_weight: 1.0
    frameworks:
      examples: ["react", "vue", "angular", "django", "flask", "express", "spring"]
      importance_weight: 0.8

    expertise_areas:
      security:
        examples: ["penetration_testing", "vulnerability_assessment", "compliance"]
        importance_weight: 1.0
        domain_matching: "security"
      cloud_platforms:
        examples: ["aws", "azure", "gcp", "heroku", "digitalocean"]
        importance_weight: 0.8
        domain_matching: "infrastructure"

    tools:
      mcp_tools:
        examples: ["context7", "magic", "playwright", "tavily"]
        importance_weight: 0.6
      system_tools:
        examples: ["bash", "file_operations", "web_search", "terminal", "debugging"]
        importance_weight: 0.4"

# Enhanced Performance Tracking
performance_tracking:
  execution_metrics:
  agent_performance:
    metrics:
      - success_rate
      - response_times
      - quality_scores
      - user_satisfaction
    learning_metrics:
      - pattern_recognition_accuracy
      - adaptation_success_rate
      - model_performance

  system_metrics:
    resource_utilization:
      - CPU usage
      - memory usage
      - network bandwidth
    performance_metrics:
      - response_times
      - throughput
      - error_rates
    quality_metrics:
      - success_rate
      - satisfaction_scores
      - efficiency_scores

# Enhanced Fallback Mechanisms
fallback_system:
  automatic_fallback:
    agent_unavailable:
      action: "select_alternative_agent"
      fallback_strategies:
        - lower_confidence_threshold: 0.2
        - enable_cross_domain_fallback: true
        use_master_agent_as_last_resort: true
        fallback_to_claude_native: true

    invalid_registration:
      action: "attempt_basic_registration"
      strategies:
        - relax_validation_rules
        - try_basic_name_validation
        - fallback_to_master_agent"

    system_failure:
      action: "emergency_fallback"
      strategies:
        - use_master_agent_direct
        - fallback_to_claude_native
        - basic_functionality_only: true

# Learning and Adaptation
learning_system:
  pattern_recognition:
  enabled: true
  feedback_integration: true
  learning_rate: 0.1
  confidence_threshold: 0.7
  success_rate_target: 0.85

  model_optimization:
  enabled: true
  update_frequency: "weekly"
  learning_rate: 0.1
  performance_target: "improvement"

  integration_points:
  input_sources:
    dynamic_agent_discovery: "Agent discovery and registration"
    agent_selection_system: "Enhanced agent selection with TF-IDF integration"
    domain_system: "Domain expertise mapping and classification"
    performance_tracking: "Historical performance data for learning"

  output_destinations:
    learning_system: "Performance feedback and model updates"
    monitoring_dashboard: "Real-time performance monitoring"
    optimization_engine: "Performance optimization recommendations"

  system_dependencies:
    dynamic_agent_discovery: "Dynamic agent discovery and registration"
    agent_selection_system: "Enhanced agent selection with TF-IDF integration"
    domain_system: "Domain expertise and specialization mapping"
    task_analysis_system: "Enhanced task analysis for agent matching"
    performance_tracking: "Performance data for learning"

# Version Management and Compatibility
version_management:
  current_version: "0.2.2"
  architecture_version: "consolidated_v2"
  compatibility_requirements:
    minimal_system_version: "0.2.0"
    required_components: ["task_analysis", "agent_selection", "clarification_system", "coordination_system"]

  consolidation_changes:
    what_was_consolidated:
      - "dynamic_agent_discovery.yaml + agent_types.yaml + agent_name_resolution.yaml → discovery/agent_registry.yaml"
      - "domain_system.yaml + agent_expertise mapping → discovery/domain_system.yaml"
      - "mcp_registry.yaml + tool management" → discovery/mcp_integration.yaml"

    benefits_of_consolidation:
      - **Dynamic agent discovery** with auto-discovery capabilities
      - **Enhanced domain expertise** mapping with semantic analysis
      - **Improved agent availability** tracking and management
      - **Intelligent fallback mechanisms** for reliability
      - **Learning integration** for continuous improvement

  migration_support:
    previous_version_support: true
    migration_strategy: "enhanced_features_with_backward_compatibility"
    configuration_migration: "automatic_with_validation_and_learning"

# Configuration Management
configuration_management:
  registry_backup:
    enabled: true
    backup_frequency: "hourly"
    backup_retention: "7 days"
    backup_path: "config/dynamic/domain_registry_backup.yaml"

  registry_updates:
    auto_update: true
    update_triggers:
      - agent_discovery_new_agents: true
      - configuration_changes: true
      learning_model_update: true
      performance_optimization: true
    validation_rules:
      consistency_check: true
      conflict_resolution: true

# Performance Optimization
performance_optimization:
  cache_optimization:
    enabled: true
    cache_strategy: "smart_caching"
    cache_size_limit: 100MB
    cache_ttl: 3600
    cache_validation: true
    eviction_policy: "lru"

  load_balancing:
    enabled: true
    strategy: "load_based"
    resource_optimization: true
    max_concurrent_agents: 10

  monitoring_optimization:
    enabled: true
    real_time_alerting: true
    predictive_optimization: true
    adaptive_thresholds: true

# Security Considerations
security_considerations:
  security_validation:
  - Agent authentication and authorization before registration
  - Capability validation before agent registration
  - Access control checks for sensitive operations

  privacy_protection:
  - User consent for agent registration
  - Data anonymization for sensitive information
  - Compliance with data protection regulations

  audit_trail:
  - Complete registration history
  - Modification tracking
  - Performance metrics monitoring
  - Security events logged

# Version Management and Compatibility
version_management:
  current_version: "0.2.2"
  architecture_version: "consolidated_v2"
  compatibility_requirements:
    minimal_system_version: "0.2.0"
    required_components: ["task_analysis", "agent_selection", "clarification_system", "coordination_system"]

  consolidation_changes:
  what_was_consolidated:
      - "dynamic_agent_discovery.yaml + agent_types.yaml + agent_name_resolution.yaml + mcp_registry.yaml"
      - "domain_system.yaml + agent_expertise mapping + learning_system"
      - "enhanced agent registry with dynamic capabilities"

    benefits_of_consolidation:
      - **100% coverage** of discovery functionality
      **Enhanced domain expertise** with semantic analysis
      **Dynamic agent availability tracking** with real-time updates
      **Intelligent fallback mechanisms** for reliability
      **Adaptive learning** capabilities for continuous improvement

  migration_support:
    previous_version_support: true
    migration_strategy: "enhanced_features_with_backward_compatibility"
    configuration_migration: "automatic_with_validation_and_learning"